

export enum ACTION_TYPES {
    GET_USER_CITY_WEATHER='@@HOME/GET_CITY_WEATHER',
		SET_USER_CITY_WEATHER='@@HOME/SET_CITY_WEATHER',
		SET_USER_CITY_IMAGE='@@HOME/SET_USER_CITY_IMAGE',
		GET_WEATHER_LIST='@@HOME/GET_WEATHER_LIST',
		SET_WEATHER_LIST='@@HOME/SET_WEATHER_LIST',
		GET_NEW_WEATHER_LIST_ITEM='@@HOME/GET_NEW_WEATHER_LIST_ITEM',
		SET_NEW_WEATHER_LIST_ITEM='@@HOME/SET_NEW_WEATHER_LIST_ITEM',
		DELETE_ITEM='@@HOME/DELETE_ITEM',
		SEARCH_USER_CITY_WEATHER='@@HOME/SEARCH_USER_CITY_WEATHER',
		GET_WEATHER_DETAILS='@@HOME/GET_WEATHER_DETAILS',
    SET_WEATHER_DETAILS='@@HOME/SET_WEATHER_DETAILS'
}